### ISSUE TITLE
Tartarus V2 Issues

### ISSUE THREAD

**Issue by AnTeBiOss** [bithatch/snake#2]
Hi there,
some issues with my Tartarus V2 : 
- No key bindings
- No maccros (not persistant)
- No custom colors for baklit keyboard

May I help ?

**Comment by brett-smith** [comment]
I see you've already found https://github.com/openrazer/openrazer/pull/1124 which covers the first two. Macros / bindings are very weak in the current version of Snake mainly due to the limitations of the stable version of OpenRazer.  I intended to have Snake  ready for when this is released.

As for custom colours, are you seeing the standard hardware effects, but NOT the 'Matrix' effect that lets you set any colour?  I have just checked the Tartarus V2 Fake driver (i dont own one so this is my only choice), and it appears that it doesn't have matrix capabilities. It may be you are affected by this https://github.com/openrazer/openrazer/commit/5ac3d5f535a7fc4f7dd089695a173340a83c5983.

**Comment by AnTeBiOss** [comment]
Thank you for answer, In snake I can change preloaded effects but no custom options.

**Comment by brett-smith** [comment]
Ok this is most definitely the missing 'Matrix' capability. You would be best to raise a ticket at https://github.com/openrazer/openrazer/issues. They are best placed to answer questions like this. 

I am not that familiar with the low level drivers, but I think a few things need to happen. If you are up to messing around with some Python you could try.

https://github.com/openrazer/openrazer/blob/master/daemon/openrazer_daemon/hardware/keyboards.py for a start, the definition for the TartarusV2 needs to have a `HAS_MATRIX = True`. I believe it also needs, `'set_key_row', 'set_custom_effect',` added to the `METHODS` attribute too. 

All of this is assuming the kernel driver has support. I think it may have, https://github.com/openrazer/openrazer/blob/master/driver/razerkbd_driver.c seems to contain some code for 'custom frames' for the Tartarus V2. Whether this works or not I cannot yet say.

Once this is done, Snake itself might need a small tweak to understand the matrix layout. There are currently only layouts that have widths of  16, 22 and 25 key devices. The Tartarus V2 seems to have a 6 key width layout. In theory Snake should default to a "single line matrix" and it will still be usable and able to set a custom effect.

Finally .... I have just ordered a Tartarus V2 as one of the devices I will uses as a reference for Snake development. At the moment I only have a real mouse, development for other devices is relying on the fake drivers openrazer provides. So I am motivated to get great support for this device once I get my hands on it!

**Comment by brett-smith** [comment]
This has been fixed upstream, but I still need to release a new version of Snake so the matrix size is dealt with properly.

**Comment by brett-smith** [comment]
Fixed in SNAPSHOT-145.
